source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

target 'SwiftDemoApp' do
  use_frameworks!
  pod 'GoogleMaps', '4.0.0'
  pod 'Google-Maps-iOS-Utils', :path => '../..', :testspecs => ['Tests']
end
