source 'https://cdn.cocoapods.org/'
platform :ios, '14.0'

target 'SwiftDemoApp' do
  use_frameworks!
  pod 'GoogleMaps', '8.0'
  pod 'Google-Maps-iOS-Utils', :path => '../..', :testspecs => ['Tests']
end
