on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

name: Release Please

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          token: ${{ secrets.SYNCED_GITHUB_TOKEN_REPO }}
          target-branch: main

      - name: Echo release outputs
        if: ${{ steps.release.outputs }}
        run: echo '${{ toJson(steps.release) }}'
        continue-on-error: true

  # Call the Publish workflow to publish to CocoaPods when a release is cut.
  # Note the "if" statement makes sure that publishing
  # only happens when a release is cut.
  publish:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    uses: ./.github/workflows/publish.yml
