on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: Release Please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.SYNCED_GITHUB_TOKEN_REPO }}
          release-type: simple,
            "extra-files": [
                "README.md",
                "Package.swift",
                "Google-Maps-iOS-Utils.podspec",
                "Podfile.template"
            ]
